<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="NuGet.Packaging" Version="7.6.0" />
    <PackageReference Include="NuGet.Protocol" Version="7.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreDatabase\CoreDatabase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Views\Cart\" />
    <Folder Include="Views\Checkout\" />
    <Folder Include="Views\Account\" />
    <Folder Include="Views\Contact\" />
    <Folder Include="Views\News\" />
    <Folder Include="wwwroot\image\banners\" />
    <Folder Include="wwwroot\image\brands\" />
    <Folder Include="wwwroot\image\categories\" />
    <Folder Include="wwwroot\image\avatars\" />
    <Folder Include="wwwroot\image\icons\" />
    <Folder Include="wwwroot\image\news\" />
    <Folder Include="wwwroot\image\products\" />
    <Folder Include="wwwroot\uploads\customers\" />
    <Folder Include="wwwroot\uploads\employees\" />
    <Folder Include="wwwroot\uploads\products\" />
  </ItemGroup>

</Project>
